import z from "zod";

import { FractalCollection } from "@fractal-os/plugin";

/**
 * Fractal Custom Collection: suppliers
 *
 * This file was auto-generated by Fractal.
 * Review and customize the schema and hooks below.
 *
 * @see https://zod.dev/v4 - Zod v4 documentation
 * @see fractal skills get - Learn about Fractal capabilities
 */
export default FractalCollection.create("suppliers")
  .withPatterns([".fractal/collections/suppliers/data/{id}.suppliers.json"])
  .withSchema(
    z.object({
      name: z.string(),
      documents: z.object({
        cnpj: z.string().optional(),
        ie: z.string().optional()
      }).optional(),
      segment: z.string().optional(),
      contact: z.string().optional(),
      email: z.string(),
      phone: z.string().optional(),
      postalCode: z.string().optional(),
      address: z.string().optional(),
      paymentTerms: z.string().optional(),
      notes: z.string().optional(),
      createdAt: z.string().datetime().optional()
    }),
  )
  /** Triggered after a record is created. Receives { value, fractal, workspace }. */
  // .onCreated(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered after a record is updated. Receives { value, previousValue, fractal, workspace }. */
  // .onUpdated(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered after a record is deleted. Receives { value, fractal, workspace }. */
  // .onDeleted(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered when reading a single record. Receives { value, fractal, workspace }. */
  // .onRead(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered when listing records. Receives { value, query, fractal, workspace }. */
  // .onList(async (ctx) => {
  //   return ctx.value;
  // })
  .build();
