import z from "zod";

import { FractalCollection } from "@fractal-os/plugin";
import { randomUUID } from "crypto";

/**
 * Fractal Custom Collection: events
 *
 * This file was auto-generated by Fractal.
 * Review and customize the schema and hooks below.
 *
 * @see https://zod.dev/v4 - Zod v4 documentation
 * @see fractal skills get - Learn about Fractal capabilities
 */
export default FractalCollection.create("events")
  .withIdGenerator(randomUUID)
  .withPatterns([".fractal/collections/events/data/{id}.events.json"])
  .withSchema(
    z.object({
      timestamp: z.string().datetime(),
      type: z.string().describe("Tipo do evento: email_sent, email_received, quote_received, quote_processed, status_changed, order_created, task_created, note"),
      source: z.string().describe("Origem: email, system, manual, whatsapp, tracker"),
      description: z.string().describe("Descrição amigável do evento em PT-BR"),
      metadata: z.unknown().describe("Dados adicionais flexíveis").optional(),
      actor: z.string().describe("Quem executou: 'ademar', 'felipe', 'donna', 'system'").optional(),
      customer: z.string().describe("Slug do cliente (opcional)").optional(),
      supplier: z.string().describe("Slug do fornecedor (opcional)").optional()
    }),
  )
  /** Triggered after a record is created. Receives { value, fractal, workspace }. */
  // .onCreated(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered after a record is updated. Receives { value, previousValue, fractal, workspace }. */
  // .onUpdated(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered after a record is deleted. Receives { value, fractal, workspace }. */
  // .onDeleted(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered when reading a single record. Receives { value, fractal, workspace }. */
  // .onRead(async (ctx) => {
  //   return ctx.value;
  // })
  /** Triggered when listing records. Receives { value, query, fractal, workspace }. */
  // .onList(async (ctx) => {
  //   return ctx.value;
  // })
  .build();
