import z from "zod"

import { FractalCollection } from "@fractal-os/plugin"

/**
 * Fractal Custom Collection: customers
 *
 * This file was auto-generated by Fractal.
 * Review and customize the schema and hooks below.
 *
 * @see https://zod.dev/v4 - Zod v4 documentation
 * @see fractal skills get - Learn about Fractal capabilities
 */
export default FractalCollection.create("customers")
  .withPatterns([".fractal/collections/customers/data/{id}.customers.json"])
  .withSchema(
    z.object({
      slug: z.string(),
      name: z.string(),
      segment: z.string().optional(),
      // Endereços da obra
      addresses: z
        .object({
          delivery: z.string().optional(), // Endereço de entrega dos materiais
          billing: z.string().optional(), // Endereço de cobrança/faturamento
        })
        .optional(),

      postalCode: z.string().optional(),
      phone: z.string().optional(),
      billingEmail: z.string().optional(),
      ie: z.string().optional(),
      client: z.string().optional(),
      document: z.string().optional(),
      engineer: z.string().optional(),
      status: z.string().optional(),
      notes: z.string().optional(),

      // Templates da obra
      templates: z
        .object({
          order: z.string(), // Caminho do template Excel para pedidos (ex: ".fractal/collections/quotes/assets/MODELO_DE_PEDIDO_GERAL_DEMA.xlsx")
        })
        .optional(),

      // Regime de materiais da obra
      // - contract: Dema compra com verba pré-aprovada; cada pedido aprovado pelo cliente abate do saldo
      // - owner:    Cliente compra os materiais direto; Dema só executa
      budget: z
        .object({
          type: z.enum(["contract", "owner"]),
          budget: z.number().optional(),
          notes: z.string().optional(),
        })
        .optional(),

      createdAt: z.string().datetime().optional(),
    })
  )
  // .onCreated(async (ctx) => {
  //   return ctx.value;
  // })
  // .onUpdated(async (ctx) => {
  //   return ctx.value;
  // })
  // .onDeleted(async (ctx) => {
  //   return ctx.value;
  // })
  // .onRead(async (ctx) => {
  //   return ctx.value;
  // })
  // .onList(async (ctx) => {
  //   return ctx.value;
  // })
  .build()
